### ISSUE TITLE
Newline in messageTemplate causes no logevent is stored

### ISSUE THREAD

**Issue by BoGrevyDynatest** [serilog/serilog-sinks-azuretablestorage#10]
If there is a newline in the messageTemplate, which often is the case for a StackTrace, the message will not be stored in the azuretable.
Just adding a .Replace("\r\n", " ") to the message will solve the problem.

**Comment by nblumhardt** [comment]
Thanks for the report. A PR would be welcome for this, if you are able to give one a shot. Cheers!

**Comment by mattruma** [comment]
Any thoughts on getting this fixed? Makes the sink almost unusable.

**Comment by nblumhardt** [comment]
Hi Matt, thanks for the note. Yes, a PR would be welcome if you have a chance to submit one. (Testing is a bit of a bottleneck at our end).

**Comment by Arznaar** [comment]
So this task is on hold? As far as i see - right now we have PR with merge conflict and almost unusable sink (any LogError with exception object is not logged in table).

**Comment by nblumhardt** [comment]
Thanks for the nudge, @Arznaar.

No, it'd be great to move this one forwards. I am not 100% sure the PR is addressing the same issue, since it mentions row keys and not messages, but perhaps the description of this issue is inaccurate?

(The main problem is that no one on the maintainers list for the sink is actively using it day-to-day, as far as I can tell. It's not a great situation, unfortunately.)

I'll see if I can get the linked PR merged to `dev` - any feedback/validation of the results would be welcome 👍

**Comment by nblumhardt** [comment]
The PR is out to NuGet as the latest dev package. If anyone can confirm the issue fixed, I'll push the 4.0 release.
