### ISSUE TITLE
Deploying ASP.NET 5 RC1 WebApi with Azure Storage Library 6.2.0 or 6.2.2 preview causing 500 error

### ISSUE THREAD

**Issue by steve-warwick** [serilog/serilog-sinks-azuretablestorage#6]
See the following stack overflow issue: [http://stackoverflow.com/questions/36484918/deploying-asp-net-5-rc1-webapi-with-azure-storage-library-6-2-0-or-6-2-2-preview](url)

**Comment by nblumhardt** [comment]
Thanks for the link. It looks like the dependency versions in this package need an update; there's a PR under discussion here: https://github.com/serilog/serilog-sinks-azuretablestorage/pull/4 - weighing in and checking out whether it addresses your issue would help move this forward.

**Comment by Bertk** [comment]
This issue is outdated - latest [Azure SDK - Storage V12.x](https://docs.microsoft.com/en-us/dotnet/api/overview/azure/storage)
All other Azure SDK Storage packages are deprecated ([WindowsAzure.storage](https://www.nuget.org/packages/WindowsAzure.Storage/), [Microsoft.Azure.Storage.*](https://www.nuget.org/packages/Microsoft.Azure.Storage.Common/))

**Comment by nblumhardt** [comment]
Thanks @Bertk
